name: Docker Action

on: [workflow_dispatch]

jobs:
  docker-action:
    name: Running Docker Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Docker Action
        uses: ./github/action/hello-world-docker-action
        with:
          who-to-greet: @super-linters
      - name: Print Outputs 
